# Generated by Django 4.0.1 on 2022-01-15 05:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Booper', '0002_rename_user_siteuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
